name: bidars
version: 0.1.1
description: **Bidars**, **B**risk **I**nterchange-purpose **D**ata-language with **A**ttributes and **R**ewireble **S**tructure, is a lightweight data markup language inspired from such as Yaml, XML, Rua.
author: Haruka Sato <as.he.that.doth.serve@gmail.com>
homepage: https://hal.dev-pack.org/project/DartPkgs/bidars/
documentation: https://hal.dev-pack.org/project/DartPkgs/bidars/docs
repository: https://github.com/halka9000stg/LeCastleDart
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  yaml: ^3.1.3
  complex: ^0.8.0
  color: ^3.0.0
  rational: ^2.2.3
  fraction: ^5.0.5
topics:
  - bidars
  - data-language
  - markup-language
  - lightweight